apiVersion: v1
kind: Secret
metadata:
  name: jenkins-admin
  namespace: jenkins
type: Opaque
data:
  jenkins-username: YWRtaW4=        # base64 of 'admin'
  jenkins-password: YWRtaW4xMjM=    # base64 of 'admin123'
