apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mysite.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mysite.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "mysite.name" . }}
      annotations:
        # checksum annotation so Helm/Argo will trigger pod rollout when index.html changes
        checksum/config: "{{ .Files.Get "files/index.html" | sha256sum }}"
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
      volumes:
      - name: html
        configMap:
          name: {{ include "mysite.fullname" . }}-html
