apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mysite.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: mysite.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "mysite.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
