apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysite
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Raheeba-cloud/jenkin-pipeline.git'
    targetRevision: main
    path: charts/mysite
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mysite
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
