apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysite
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/raheeba/jenkins-pipeline.git'
    path: charts/mysite
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: mysite
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
